include::_header.adoc[]


[[cl_khr_d3d11_sharing]]
= cl_khr_d3d11_sharing

Provide interoperability between OpenCL and Direct3D 11.

----
#pragma OPENCL EXTENSION cl_khr_d3d11_sharing : enable
----


[[description]]
== Description

The goal of this extension is to provide interoperability between OpenCL and Direct3D 11.
This is designed to function analogously to the <<cl_khr_gl_sharing.adoc#, OpenGL interoperability>> as defined in sections 9.7 and 9.8.
If this extension is supported by an implementation, the string "cl_khr_d3d11_sharing" will be present in the `CL_PLATFORM_EXTENSIONS` or `CL_DEVICE_EXTENSIONS` string described in the table of allowed values for `param_name` for <<clGetDeviceInfo.adoc#, `clGetDeviceInfo`>> or <<clGetPlatformInfo.adoc#, `clGetPlatformInfo`>>.

As currently proposed, the interfaces for this extension are provided in the header file `cl_d3d11.h`.

If the `cl_khr_d3d11_sharing` extension is supported, then the following functions are enabled:

* <<clGetDeviceIDsFromD3D11KHR.adoc#, `clGetDeviceIDsFromD3D11KHR`>>

* <<clCreateFromD3D11BufferKHR.adoc#, `clCreateFromD3D11BufferKHR`>>

* <<clCreateFromD3D11Texture2DKHR.adoc#, `clCreateFromD3D11Texture2DKHR`>>

* <<clCreateFromD3D11Texture3DKHR.adoc#, `clCreateFromD3D11Texture3DKHR`>>

* <<clEnqueueAcquireD3D11ObjectsKHR.adoc#, `clEnqueueAcquireD3D11ObjectsKHR`>>

* <<clEnqueueReleaseD3D11ObjectsKHR.adoc#, `clEnqueueReleaseD3D11ObjectsKHR`>>

The OpenCL functions enabled by the `cl_khr_d3d11_sharing` extension allow applications to use Direct3D 11 resources as OpenCL memory objects.
This allows efficient sharing of data between OpenCL and Direct3D 11.
The OpenCL API may be used to execute kernels that read and/or write memory objects that are also Direct3D 11 resources.
An OpenCL image object may be created from a Direct3D 11 texture resource.
An OpenCL buffer object may be created from a Direct3D 11 buffer resource.
OpenCL memory objects may be created from Direct3D 11 objects if and only if the OpenCL context has been created from a Direct3D 11 device.

.Lifetime of Shared [D3D11] Objects

An OpenCL memory object created from a Direct3D 11 resource remains valid as long as the corresponding Direct3D 11 resource has not been deleted.
If the Direct3D 11 resource is deleted through the Direct3D 11 API, subsequent use of the OpenCL memory object will result in undefined behavior, including but not limited to possible OpenCL errors, data corruption, and program termination.

The successful creation of a cl_context against a Direct3D 11 device specified via the context create parameter `CL_CONTEXT_D3D11_DEVICE_KHR` will increment the internal Direct3D reference count on the specified Direct3D 11 device.
The internal Direct3D reference count on that Direct3D 11 device will be decremented when the OpenCL reference count on the returned OpenCL context drops to zero.

The OpenCL context and corresponding command-queues are dependent on the existence of the Direct3D 11 device from which the OpenCL context was created.
If the Direct3D 11 device is deleted through the Direct3D 11 API, subsequent use of the OpenCL context will result in undefined behavior, including but not limited to possible OpenCL errors, data corruption, and program termination.


:spec-name: Ext
:spec-page: 95


[[seealso]]
== Also see

<<EXTENSION.adoc#, EXTENSION>>, <<clGetDeviceIDsFromD3D11KHR.adoc#, `clGetDeviceIDsFromD3D11KHR`>>, <<clCreateFromD3D11BufferKHR.adoc#, `clCreateFromD3D11BufferKHR`>>, <<clCreateFromD3D11Texture2DKHR.adoc#, `clCreateFromD3D11Texture2DKHR`>>, <<clCreateFromD3D11Texture3DKHR.adoc#, `clCreateFromD3D11Texture3DKHR`>>, <<clEnqueueAcquireD3D10ObjectsKHR.adoc#, `clEnqueueAcquireD3D10ObjectsKHR`>>, <<clEnqueueReleaseD3D11ObjectsKHR.adoc#, `clEnqueueReleaseD3D11ObjectsKHR`>>

include::_footer.adoc[]
