include::_header.adoc[]


[[clCreateBuffer]]
= clCreateBuffer

Creates a buffer object.

[source,c]
----
cl_mem clCreateBuffer(cl_context context,
                      cl_mem_flags flags,
                      size_t size,
                      void *host_ptr,
                      cl_int *errcode_ret)
----


[[parameters]]
== Parameters

`context`::

A valid OpenCL context used to create the buffer object.

`flags`::

+
--

A bit-field that is used to specify allocation and usage information such as the memory arena that should be used to allocate the buffer object and how it will be used.
The following table describes the possible values for `flags`.
If value specified for `flags` is 0, the default is used which is `CL_MEM_READ_WRITE`.

include::clCreate_memflagsInc.adoc[]

--

`size`::

The size in bytes of the buffer memory object to be allocated.

`host_ptr`::

A pointer to the buffer data that may already be allocated by the application.
The size of the buffer that `host_ptr` points to must be ≥ `size` bytes.

`errcode_ret`::

Returns an appropriate error code.
If `errcode_ret` is NULL, no error code is returned.


[[notes]]
== Notes

The user is responsible for ensuring that data passed into and out of OpenCL images are natively aligned relative to the start of the buffer as per kernel language or IL requirements.
OpenCL buffers created with `CL_MEM_USE_HOST_PTR` need to provide an appropriately aligned host memory pointer that is aligned to the data types used to access these buffers in a kernel(s).

If `clCreateBuffer` is called with a pointer returned by `clSVMAlloc` as its `host_ptr` argument, and `CL_MEM_USE_HOST_PTR` is set in its `flags` argument, `clCreateBuffer` will succeed and return a valid non-zero buffer object as long as the `size` argument to `clCreateBuffer` is no larger than the `size` argument passed in the original `clSVMAlloc` call.
The new buffer object returned has the shared memory as the underlying storage.
Locations in the buffer's underlying shared memory can be operated on using atomic operations to the device's level of support as defined in the memory model.


[[errors]]
== Errors

Returns a valid non-zero buffer object and `errcode_ret` is set to `CL_SUCCESS` if the buffer object is created successfully.
Otherwise, it returns a NULL value with one of the following error values returned in `errcode_ret`:

* `CL_INVALID_CONTEXT` if `context` is not a valid context.

* `CL_INVALID_VALUE` if values specified in `flags` are not valid as defined in the table above.

* {blank}
+
--

`CL_INVALID_BUFFER_SIZE` if `size` is 0.

Implementations may return `CL_INVALID_BUFFER_SIZE` if `size` is greater than the `CL_DEVICE_MAX_MEM_ALLOC_SIZE` value specified in the table of allowed values for `param_name` for <<clGetDeviceInfo.adoc#, `clGetDeviceInfo`>> for all `devices` in context.

--

* `CL_INVALID_HOST_PTR` if `host_ptr` is NULL and `CL_MEM_USE_HOST_PTR` or `CL_MEM_COPY_HOST_PTR` are set in `flags` or if `host_ptr` is not NULL but `CL_MEM_COPY_HOST_PTR` or `CL_MEM_USE_HOST_PTR` are not set in `flags`.

* `CL_MEM_OBJECT_ALLOCATION_FAILURE` if there is a failure to allocate memory for buffer object.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 104


[[seealso]]
== Also see

<<clEnqueueReadBuffer.adoc#, `clEnqueueReadBuffer`>>, <<clEnqueueWriteBuffer.adoc#, `clEnqueueWriteBuffer`>>, <<clEnqueueCopyBuffer.adoc#, `clEnqueueCopyBuffer`>>, <<clCreateSubBuffer.adoc#, `clCreateSubBuffer`>>, <<classDiagram.adoc#, Cardinality Diagram>>

include::_footer.adoc[]
