include::_header.adoc[]


[[clEnqueueReleaseDX9MediaSurfacesKHR]]
= clEnqueueReleaseDX9MediaSurfacesKHR

Release OpenCL memory objects that have been created from media surfaces.

[source,c]
----
cl_int clEnqueueReleaseDX9MediaSurfacesKHR(cl_command_queue command_queue,
                                           cl_uint num_objects,
                                           const cl_mem *mem_objects,
                                           cl_uint num_events_in_wait_list,
                                           const cl_event *event_wait_list,
                                           cl_event *event)
----


[[parameters]]
== Parameters

`command_queue`::

A valid command-queue.

`num_objects`::

The number of memory objects to be released in `mem_objects`.

`mem_objects`::

A pointer to a list of OpenCL memory objects that were created from media surfaces.

`num_events_in_wait_list`, `event_wait_list`::

Specify events that need to complete before this particular command can be executed.
If `event_wait_list` is NULL, then this particular command does not wait on any event to complete.
If `event_wait_list` is NULL, `num_events_in_wait_list` must be 0.
If `event_wait_list` is not NULL, the list of events pointed to by `event_wait_list` must be valid and `num_events_in_wait_list` must be greater than 0.
The events specified in `event` returns an event object that identifies this particular command and can be used to query or queue a wait for this particular command to complete.
`event` can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete.
If the `event_wait_list` and the event arguments are not NULL, the `event` argument should not refer to an element of the `event_wait_list` array.


[[notes]]
== Notes

Used to release OpenCL memory objects that have been created from media surfaces.
The media surfaces are released by the OpenCL context associated with `command_queue`.

OpenCL memory objects created from media surfaces which have been acquired by OpenCL must be released by OpenCL before they may be accessed by the media adapter API.
Accessing a media surface while its corresponding OpenCL memory object is acquired is in error and will result in undefined behavior, including but not limited to possible OpenCL errors, data corruption, and program termination.

If `CL_CONTEXT_INTEROP_USER_SYNC` is not specified as `CL_TRUE` during context creation, `clEnqueueReleaseDX9MediaSurfacesKHR` provides the synchronization guarantee that any calls to media adapter APIs involving the interop device(s) used in the OpenCL context made after the call to `clEnqueueReleaseDX9MediaSurfacesKHR` will not start executing until after all events in `event_wait_list` are complete and all work already submitted to `command_queue` completes execution.
If the context was created with properties specifying `CL_CONTEXT_INTEROP_USER_SYNC` as `CL_TRUE`, the user is responsible for guaranteeing that any media adapter API calls involving the interop device(s) used in the OpenCL context made after `clEnqueueReleaseDX9MediaSurfacesKHR` will not start executing until after event returned by `clEnqueueReleaseDX9MediaSurfacesKHR` reports completion.

include::sharingDX9Inc.adoc[]


[[errors]]
== Errors

Returns `CL_SUCCESS` returns `CL_SUCCESS` if the function is executed successfully.
If `num_objects` is 0 and <`mem_objects`> is NULL then the function does nothing and returns `CL_SUCCESS`.
Otherwise it returns one of the following errors:

* `CL_INVALID_VALUE` if `num_objects` is zero and `mem_objects` is not a NULL value or if `num_objects` > 0 and `mem_objects` is NULL.

* `CL_INVALID_MEM_OBJECT` if memory objects in `mem_objects` are not valid OpenCL memory objects or if memory objects in `mem_objects` have not been created from valid media surfaces.

* `CL_INVALID_COMMAND_QUEUE` if `command_queue` is not a valid command-queue.

* `CL_INVALID_CONTEXT` if context associated with `command_queue` was not created from a media object.

* `CL_DX9_MEDIA_SURFACE_NOT_ACQUIRED_KHR` if memory objects in `mem_objects` have not been previously been acquired using <<clEnqueueAcquireDX9MediaSurfacesKHR.adoc#, `clEnqueueAcquireDX9MediaSurfacesKHR`>> or have been released using `clEnqueueReleaseDX9MediaSurfacesKHR` since the last time that they were acquired.

* `CL_INVALID_EVENT_WAIT_LIST` if `event_wait_list` is NULL and `num_event_in_wait_list` > 0, or `event_wait_list` is not NULL and `num_event_in_wait_list` is 0, or if event objects in `event_wait_list` are not valid events.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Ext
:spec-page: 91


[[seealso]]
== Also see

<<cl_khr_dx9_media_sharing.adoc#, `cl_khr_dx9_media_sharing`>>

include::_footer.adoc[]
