include::_header.adoc[]


[[clEnqueueAcquireEGLObjectsKHR]]
= clEnqueueAcquireEGLObjectsKHR

Acquire OpenCL memory objects that have been created from EGL resources.

[source,c]
----
cl_int clEnqueueAcquireEGLObjectsKHR(cl_command_queue command_queue,
                                     cl_uint num_objects,
                                     const cl_mem *mem_objects,
                                     cl_uint num_events_in_wait_list,
                                     const cl_event *event_wait_list,
                                     cl_event *event)
----


[[parameters]]
== Parameters

`command_queue`::

A valid command-queue.

`num_objects`::

The number of memory objects to be acquired in `mem_objects`.

`mem_objects`::

A pointer to a list of OpenCL memory objects that were created from EGL resources, within the context associate with `command_queue`.

`event_wait_list` `num_events_in_wait_list`::

Specify events that need to complete before this particular command can be executed.
If `event_wait_list` is NULL, then this particular command does not wait on any event to complete.
If `event_wait_list` is NULL, `num_events_in_wait_list` must be 0.
If `event_wait_list` is not NULL, the list of events pointed to by `event_wait_list` must be valid and `num_events_in_wait_list` must be greater than 0.
The events specified in `event_wait_list` act as synchronization points.

`event`::

Returns an event object that identifies this command and can be used to query or queue a wait for the command to complete.
`event` can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete.


[[description]]
== Description

This function is used to acquire OpenCL memory objects that have been created from EGL resources.
The EGL objects are acquired by the OpenCL context associated with `command_queue` and can therefore be used by all command-queues associated with the OpenCL context.

OpenCL memory objects created from EGL resources must be acquired before they can be used by any OpenCL commands queued to a command-queue.
If an OpenCL memory object created from a EGL resource is used while it is not currently acquired by OpenCL, the call attempting to use that OpenCL memory object will return `CL_EGL_RESOURCE_NOT_ACQUIRED_KHR`.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the function is executed successfully.
If `num_objects` is 0 and `mem_objects` is NULL the function does nothing and returns `CL_SUCCESS`.
Otherwise, it returns one of the following errors:

* `CL_INVALID_VALUE` if `num_objects` is zero and `mem_objects` is not a NULL value or if `num_objects` > 0 and `mem_objects` is NULL.

* `CL_INVALID_MEM_OBJECT` if memory objects in `mem_objects` are not valid OpenCL memory objects in the context associated with `command_queue`.

* `CL_INVALID_EGL_OBJECT_KHR` if memory objects in `mem_objects` have not been created from EGL resources.

* `CL_INVALID_COMMAND_QUEUE` if `command_queue` is not a valid command-queue.

* `CL_INVALID_EVENT_WAIT_LIST` if `event_wait_list` is NULL and `num_events_in_wait_list` > 0, or `event_wait_list` is not NULL and `num_events_in_wait_list` is 0, or if event objects in `event_wait_list` are not valid events.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Ext
:spec-page: 169


[[seealso]]
== Also see

<<cl_khr_egl_image.adoc#, `cl_khr_egl_image`>>, <<cl_khr_egl_event.adoc#, `cl_khr_egl_event`>>, <<clEnqueueReleaseEGLObjectsKHR.adoc#, `clEnqueueReleaseEGLObjectsKHR`>>, <<clCreateFromEGLImageKHR.adoc#, `clCreateFromEGLImageKHR`>>

include::_footer.adoc[]
