include::_header.adoc[]


[[clEnqueueSVMMap]]
= clEnqueueSVMMap

Enqueues a command that will allow the host to update a region of a SVM buffer

[source,c]
----
cl_int clEnqueueSVMMap(cl_command_queue command_queue,
                       cl_bool blocking_map,
                       cl_map_flags map_flags,
                       void *svm_ptr,
                       size_t size,
                       cl_uint num_events_in_wait_list,
                       const cl_event *event_wait_list,
                       cl_event *event)
----


[[parameters]]
== Parameters

`command_queue`::

Must be a valid host command-queue.

`blocking_map`::

+
--

Indicates if the map operation is `blocking` or `non-blocking`.

If `blocking_map` is `CL_TRUE`, `clEnqueueSVMMap` does not return until the application can access the contents of the SVM region specified by `svm_ptr` and `size` on the host.

If `blocking_map` is `CL_FALSE` i.e.
map operation is non-blocking, the region specified by `svm_ptr` and `size` cannot be used until the map command has completed.
The `event` argument returns an event object which can be used to query the execution status of the map command.
When the map command is completed, the application can access the contents of the region specified by `svm_ptr` and `size`.

--

`map_flags`::

+
--

A bit-bield with the following supported values.

include::map_flags_Inc.adoc[]

--

`svm_ptr` and `size`::

A pointer to a memory region and size in bytes that will be updated by the host.
If `svm_ptr` is allocated using <<clSVMAlloc.adoc#, `clSVMAlloc`>> then it must be allocated from the same context from which `command_queue` was created.
Otherwise the behavior is undefined.

`event_wait_list,` `num_events_in_wait_list`::

Specify events that need to complete before this particular command can be executed.
If `event_wait_list` is NULL, then this particular command does not wait on any event to complete.
If `event_wait_list` is NULL, `num_events_in_wait_list` must be 0.
If `event_wait_list` is not NULL, the list of events pointed to by `event_wait_list` must be valid and `num_events_in_wait_list` must be greater than 0.
The events specified in `event_wait_list` act as synchronization points.
The context associated with events in `event_wait_list` and `command_queue` must be the same.
The memory associated with `event_wait_list` can be reused or freed after the function returns.

`event`::

Returns an event object that identifies this particular command and can be used to query or queue a wait for this particular command to complete.
`event` can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete.
<<clEnqueueBarrierWithWaitList.adoc#, `clEnqueueBarrierWithWaitList`>> can be used instead.
If the `event_wait_list` and the `event` arguments are not NULL, the `event` argument should not refer to an element of the `event_wait_list` array.


[[notes]]
== Notes

Note that since we are enqueuing a command with a SVM buffer, the region is already mapped in the host address space.

<<clEnqueueSVMMap.adoc#, `clEnqueueSVMMap`>>, and <<clEnqueueSVMUnmap.adoc#, `clEnqueueSVMUnmap`>> act as synchronization points for the region of the SVM buffer specified in these calls.


[[errors]]
== Errors

`clEnqueueSVMMap` returns `CL_SUCCESS` if the function is executed successfully.
Otherwise, it returns one of the following errors:

* `CL_INVALID_COMMAND_QUEUE` if `command_queue` is not a valid host command-queue.

* `CL_INVALID_CONTEXT` if the context associated with `command_queue` and events in `event_wait_list` are not the same.

* `CL_INVALID_VALUE` if `svm_ptr` is NULL.

* `CL_INVALID_VALUE` if `size` is 0 or if values specified in `map_flags` are not valid.

* `CL_INVALID_EVENT_WAIT_LIST` if `event_wait_list` is NULL and `num_events_in_wait_list` > 0, or `event_wait_list` is not NULL and `num_events_in_wait_list` is 0, or if event objects in `event_wait_list` are not valid events.

* `CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST` if the map operation is blocking and the execution status of any of the events in `event_wait_list` is a negative integer value.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 184


[[seealso]]
== Also see

<<sharedVirtualMemory.adoc#, Shared Virtual Memory Functions>>

include::_footer.adoc[]
