include::_header.adoc[]


[[clFlush]]
= clFlush

Issues all previously queued OpenCL commands in a command-queue to the device associated with the command-queue.

[source,c]
----
cl_int clFlush(cl_command_queue command_queue)
----


[[notes]]
== Notes

Issues all previously queued OpenCL commands in `command_queue` to the device associated with `command_queue`.

`clFlush` only guarantees that all queued commands to `command_queue` will eventually be submitted to the appropriate device There is no guarantee that they will be complete after `clFlush` returns.

Any blocking commands queued in a command-queue and <<clReleaseCommandQueue.adoc#, `clReleaseCommandQueue`>> perform an implicit flush of the command-queue.
These blocking commands are <<clEnqueueReadBuffer.adoc#, `clEnqueueReadBuffer`>>, <<clEnqueueReadBufferRect.adoc#, `clEnqueueReadBufferRect`>>, <<clEnqueueReadImage.adoc#, `clEnqueueReadImage`>>, with `blocking_read` set to `CL_TRUE`; <<clEnqueueWriteBuffer.adoc#, `clEnqueueWriteBuffer`>>, <<clEnqueueWriteBufferRect.adoc#, `clEnqueueWriteBufferRect`>>, <<clEnqueueWriteImage.adoc#, `clEnqueueWriteImage`>> with `blocking_write` set to `CL_TRUE`; <<clEnqueueMapBuffer.adoc#, `clEnqueueMapBuffer`>>, <<clEnqueueMapImage.adoc#, `clEnqueueMapImage`>> with `blocking_map` set to `CL_TRUE`; <<clEnqueueSVMMemcpy.adoc#, `clEnqueueSVMMemcpy`>> with `blocking_copy` set to `CL_TRUE`; <<clEnqueueSVMMap.adoc#, `clEnqueueSVMMap`>> with `blocking_map` set to `CL_TRUE` or <<clWaitForEvents.adoc#, `clWaitForEvents`>>.

To use event objects that refer to commands enqueued in a command-queue as event objects to wait on by commands enqueued in a different command-queue, the application must call a `clFlush` or any blocking commands that perform an implicit flush of the command-queue where the commands that refer to these event objects are enqueued.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the function call was executed successfully.
Otherwise, it returns one of the following errors:

* `CL_INVALID_COMMAND_QUEUE` if `command_queue` is not a valid host command-queue.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 266


[[seealso]]
== Also see

<<clFinish.adoc#, `clFinish`>>

include::_footer.adoc[]
