include::_header.adoc[]


[[clGetDeviceAndHostTimer]]
= clGetDeviceAndHostTimer

Returns a reasonably synchronized pair of timestamps from the device timer and the host timer as seen by device.

[source,c]
----
cl_int clGetDeviceAndHostTimer(cl_device_id device,
                               cl_ulong * device_timestamp,
                               cl_ulong * host_timestamp)
----


[[parameters]]
== Parameters

`device`::

A device returned by <<clGetDeviceIDs.adoc#, `clGetDeviceIDs`>>.

`device_timestamp`::

Will be updated with the value of the current timer in nanoseconds.
The resolution of the timer is the same as the device profiling timer returned by <<clGetDeviceInfo.adoc#, `clGetDeviceInfo`>> and the `CL_DEVICE_PROFILING_TIMER_RESOLUTION` query.

`host_timestamp`::

Will be updated with the value of the current timer in nanoseconds at the closest possible point in time to that at which `device_timer` was returned.
The resolution of the timer may be queried via <<clGetPlatformInfo.adoc#, `clGetPlatformInfo`>> and the flag `CL_PLATFORM_HOST_TIMER_RESOLUTION`.


[[notes]]
== Notes

Returns a reasonably synchronized pair of timestamps from the device timer and the host timer as seen by `device`.
Implementations may need to execute this query with a high latency in order to provide reasonable synchronization of the timestamps.
The host timestamp and device timestamp returned by this function and <<clGetHostTimer.adoc#, `clGetHostTimer`>> each have an implementation defined timebase.
The timestamps will always be in their respective timebases regardless of which query function is used.
The timestamp returned from <<clGetEventProfilingInfo.adoc#, `clGetEventProfilingInfo`>> for an event on a device and a device timestamp queried from the same device will always be in the same timebase.


[[errors]]
== Errors

`clGetDeviceAndHostTimer` will return `CL_SUCCESS` with a time value in `host_timestamp` if provided.
Otherwise, it returns one of the following errors:

* `CL_INVALID_DEVICE` if `device` is not a valid OpenCL device.

* `CL_INVALID_VALUE` if `host_timestamp` or `device_timestamp` is NULL.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 82


[[seealso]]
== Also see

<<clGetHostTimer.adoc#, `clGetHostTimer`>>, <<clGetDeviceInfo.adoc#, `clGetDeviceInfo`>>, <<clGetPlatformInfo.adoc#, `clGetPlatformInfo`>>

include::_footer.adoc[]
