include::_header.adoc[]


[[clGetGLObjectInfo]]
= clGetGLObjectInfo

Query an OpenGL object used to create an OpenCL memory object.

[source,c]
----
cl_int clGetGLObjectInfo(cl_mem memobj,
                         cl_gl_object_type *gl_object_type,
                         GLuint *gl_object_name)
----


[[parameters]]
== Parameters

`gl_object_type`::

Returns the type of GL object attached to `memobj` and can be `CL_GL_OBJECT_BUFFER`, `CL_GL_OBJECT_TEXTURE2D`, `CL_GL_OBJECT_TEXTURE3D`, `CL_GL_OBJECT_TEXTURE2D_ARRAY`, `CL_GL_OBJECT_TEXTURE1D`, `CL_GL_OBJECT_TEXTURE1D_ARRAY`, `CL_GL_OBJECT_TEXTURE_BUFFER`, or `CL_GL_OBJECT_RENDERBUFFER`.
If `gl_object_type` is NULL, it is ignored.

`gl_object_name`::

Returns the GL object name used to create `memobj`.
If `gl_object_name` is NULL, it is ignored.


[[description]]
== Description

The OpenGL object used to create the OpenCL memory object and information about the object type i.e.
whether it is a texture, renderbuffer, or buffer object can be queried using this function.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the call was executed successfully.
Otherwise, it returns one of the following errors:

* `CL_INVALID_MEM_OBJECT` if `memobj` is not a valid OpenCL memory object.

* `CL_INVALID_GL_OBJECT` if there is no GL object associated with `memobj`.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Ext
:spec-page: 53


[[seealso]]
== Also see

<<cl_khr_gl_sharing.adoc#, `cl_khr_gl_sharing`>>, <<clGetGLTextureInfo.adoc#, `clGetGLTextureInfo`>>

include::_footer.adoc[]
