include::_header.adoc[]


[[clReleaseProgram]]
= clReleaseProgram

Decrements the `program` reference count.

[source,c]
----
cl_int clReleaseProgram(cl_program program)
----


[[notes]]
== Notes

The program object is deleted after all kernel objects associated with `program` have been deleted and the `program` reference count becomes zero.

Using this function to release a reference that was not obtained by creating the object or by calling <<clRetainProgram.adoc#, `clRetainProgram`>> causes undefined behavior.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the function is executed successfully.
Otherwise, it returns one of the following errors:

* `CL_INVALID_PROGRAM` if `program` is not a valid program object.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 199


[[seealso]]
== Also see

<<clCreateProgramWithSource.adoc#, `clCreateProgramWithSource`>>, <<clCreateProgramWithBinary.adoc#, `clCreateProgramWithBinary`>>, <<clRetainProgram.adoc#, `clRetainProgram`>>

include::_footer.adoc[]
