include::_header.adoc[]


[[clReleaseCommandQueue]]
= clReleaseCommandQueue

Decrements the `command_queue` reference count.

[source,c]
----
cl_int clReleaseCommandQueue(cl_command_queue command_queue)
----


[[parameters]]
== Parameters

`command_queue`::

Specifies the command-queue to release.


[[notes]]
== Notes

After the `command_queue` reference count becomes zero and all commands queued to `command_queue` have finished (e.g., kernel executions, memory object updates, etc.), the command-queue is deleted.

`clReleaseCommandQueue` performs an implicit flush to issue any previously queued OpenCL commands in `command_queue`.
Using this function to release a reference that was not obtained by creating the object or by calling <<clRetainCommandQueue.adoc#, `clRetainCommandQueue`>> causes undefined behavior.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the function is executed successfully.
Otherwise, it returns one of the following:

* `CL_INVALID_COMMAND_QUEUE` if `command_queue` is not a valid command queue.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 100


[[seealso]]
== Also see

<<clCreateCommandQueueWithProperties.adoc#, `clCreateCommandQueueWithProperties`>>, <<clGetCommandQueueInfo.adoc#, `clGetCommandQueueInfo`>>, <<clRetainCommandQueue.adoc#, `clRetainCommandQueue`>>

include::_footer.adoc[]
