include::_header.adoc[]


[[clReleaseMemObject]]
= clReleaseMemObject

Decrements the memory object reference count.

[source,c]
----
cl_int clReleaseMemObject(cl_mem memobj)
----


[[notes]]
== Notes

After the `memobj` reference count becomes zero and commands queued for execution on a command-queue(s) that use `memobj` have finished, the memory object is deleted.
If `memobj` is a buffer object, `memobj` cannot be deleted until all sub-buffer objects associated with `memobj` are deleted.
Using this function to release a reference that was not obtained by creating the object or by calling <<clRetainMemObject.adoc#, `clRetainMemObject`>> causes undefined behavior.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the function is executed successfully.
Otherwise, it returns one of the following errors:

* `CL_INVALID_MEM_OBJECT` if `memobj` is a not a valid memory object.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 163


[[seealso]]
== Also see

<<clCreateBuffer.adoc#, `clCreateBuffer`>>, <<clEnqueueCopyBuffer.adoc#, `clEnqueueCopyBuffer`>>, <<clEnqueueReadBuffer.adoc#, `clEnqueueReadBuffer`>>, <<clEnqueueWriteBuffer.adoc#, `clEnqueueWriteBuffer`>>, <<clRetainMemObject.adoc#, `clRetainMemObject`>>

include::_footer.adoc[]
