include::_header.adoc[]


[[clSetDefaultDeviceCommandQueue]]
= clSetDefaultDeviceCommandQueue

Replaces the default command queue on the device.

[source,c]
----
cl_int clSetDefaultDeviceCommandQueue(cl_context context,
                                      cl_device_id device,
                                      cl_command_queue command_queue)
----


[[parameters]]
== Parameters

`context`::

`device`::

`command_queue`::


[[notes]]
== Notes

<<clSetDefaultDeviceCommandQueue.adoc#, `clSetDefaultDeviceCommandQueue`>> may be used to replace a default device command queue created with <<clCreateCommandQueueWithProperties.adoc#, `clCreateCommandQueueWithProperties`>> and the `CL_QUEUE_ON_DEVICE_DEFAULT` flag.


[[errors]]
== Errors

Returns `CL_SUCCESS` if the function executed successfully.
Otherwise, it returns one of the following errors:

* `CL_INVALID_CONTEXT` if `context` is not a valid context.

* `CL_INVALID_DEVICE` if `device` is not a valid device or is not associated with `context`.

* `CL_INVALID_COMMAND_QUEUE` if `command_queue` is not a valid command-queue for `device`.

* `CL_OUT_OF_RESOURCES` if there is a failure to allocate resources required by the OpenCL implementation on the device.

* `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.


:spec-name: Core
:spec-page: 99


[[seealso]]
== Also see

<<clCreateCommandQueueWithProperties.adoc#, `clCreateCommandQueueWithProperties`>>

include::_footer.adoc[]
