include::_header.adoc[]


[[__constant]]
= __constant

Address Space Qualifier.

----
__constant
constant
----


[[description]]
== Description

The `__constant` or `constant` address space name is used to describe variables allocated in global memory and which are accessed inside a kernel(s) as read-only variables.
These read-only variables can be accessed by all (global) work-items of the kernel during its execution.
Pointers to the `__constant` address space are allowed as arguments to functions (including kernel functions) and for variables declared inside functions.

All string literal storage shall be in the `__constant` address space.

NOTE: Each argument to a kernel that is a pointer to the `__constant` address space is counted separately towards the maximum number of such arguments, defined as `CL_DEVICE_MAX_CONSTANT_ARGS` are described in the table for <<clGetDeviceInfo.adoc#, `clGetDeviceInfo`>>.

Variables in the program scope must be declared in the `__constant` address space.
Variables in the outermost scope of kernel functions can be declared in the `__constant` address space.
These variables are required to be initialized and the values used to initialize these variables must be a compile time constant.
Writing to such a variable results in a compile-time error.

Implementations are not required to aggregate these declarations into the fewest number of constant arguments.
This behavior is implementation defined.

Thus portable code must conservatively assume that each variable declared inside a function or in program scope allocated in the `__constant` address space counts as a separate constant argument.


[[notes]]
== Notes

include::addressSpaceQualifiersInc.adoc[]


[[example1]]
== Example

include::qualifierExampleInc.adoc[]


:spec-name: CLan
:spec-page: 34


[[seealso]]
== Also see

<<global.adoc#, `__global`>>, <<local.adoc#, `__local`>>, <<private.adoc#, `__private`>>, <<genericAddressSpace.adoc#, `genericAddressSpace`>>, <<qualifiers.adoc#, `qualifiers`>>

include::_footer.adoc[]
