include::_header.adoc[]


[[DataTypes]]
= Data Types

OpenCL data types.


[[description]]
== Description

These are the data types available in the OpenCL C programming language.
Click on a category name in the table below to see information about specific data types.

[cols="1a,1a", options="header"]
|===

|Data type category
|Included data types

|<<scalarDataTypes.adoc#, Scalar data types>>
|`bool`, `char`, `cl_char`, `unsigned char`, `uchar`, `cl_uchar`, `short`, `cl_short`, `unsigned short`, `ushort`, `cl_ushort`, `int`, `cl_int`, `unsigned int`, `uint`, `cl_uint`, `long`, `cl_long`, `unsigned long`, `ulong`, `cl_ulong`, `float`, `size_t`, `ptrdiff_t`, `intptr_t`, `uintptr_t`, `void`, `double`, and `half` floating point types.

|<<vectorDataTypes.adoc#, Vector data types>>
|`charn`, `ucharn`, `shortn`, `ushortn`, `intn`, `uintn`, `longn`, `ulongn`, `floatn`, doublen, and optional halfn types.

|<<abstractDataTypes.adoc#, Abstract data types>>
|`cl_platform_id`, `cl_device_id`, `cl_context`, `cl_command_queue`, `cl_mem`, `cl_program`, `cl_kernel`, `cl_event`, and `cl_sampler`.

|<<reservedDataTypes.adoc#, Reserved Data Types>>
|`booln`, `halfn`, `quad`, `quadn`, `complex half`, `complex halfn`, `imaginary half`, `imaginary halfn`, `complex float`, `complex floatn`, `imaginary float`, `imaginary floatn`, `complex double`, `complex doublen`, `imaginary double`, `imaginary doublen`, `complex quad`, `complex quadn`, `imaginary quad`, `imaginary quadn`, `floatn`x_m_, `doublen`x_m_, `long double`, `long doublen`, `long long`, `long longn`, `unsigned long long`, `ulong long`, and `ulong longn`.

|<<otherDataTypes.adoc#, Other data types>>
|`image2d_t`, `image3d_t`, `image2d_array_t`, `image1d_t`, `image1d_buffer_t`, `image1d_array_t`, `image2d_depth_t`, `image2d_array_depth_t`, `sampler_t`, `queue_t`, `ndrange_t`, `clk_event_t`, `reserve_id_t`, `event_t`, `cl_mem_fence_flags`, `image2d_array_msaa_t_t`, `image2d_msaa_depth_t_t`, and `image2d_array_msaa_depth_t_t`.

|===


[[notes]]
== Alignment of Types

A data item declared to be a data type in memory is always aligned to the size of the data type in bytes.
For example, a `float4` variable will be aligned to a 16-byte boundary, and a `char2` variable will be aligned to a 2-byte boundary.

For 3-component vector data types, the size of the data type is `4 * sizeof(component)`.
This means that a 3-component vector data type will be aligned to a `4 * sizeof(component)` boundary.
The <<vloadn.adoc#, `vload3`>> and <<vstoren.adoc#, `vstore3`>> built-in functions can be used to read and write, respectively, 3-component vector data types from an array of packed scalar data type.

A built-in data type that is not a power of two bytes in size must be aligned to the next larger power of two.
This rule applies to built-in types only, not `structs` or `unions`.

The OpenCL compiler is responsible for aligning data items to the appropriate alignment as required by the data type.
For arguments to a <<functionQualifiers.adoc#, `__kernel`>> function declared to be a pointer to a data type, the OpenCL compiler can assume that the pointee is always appropriately aligned as required by the data type.
The behavior of an unaligned load or store is undefined, except for the <<vloadn.adoc#, `vloadn`>>, <<vload_halfn.adoc#, `vload_halfn`>>, <<vstoren.adoc#, `vstoren`>>, and <<vstore_halfn.adoc#, `vstore_halfn`>> functions.
The vector load functions can read a vector from an address aligned to the element type of the vector.
The vector store functions can write a vector to an address aligned to the element type of the vector.

.Alignment of Application Data Types

The user is responsible for ensuring that data passed into and out of OpenCL buffers are natively aligned relative to the start of the buffer as described above.
This implies that OpenCL buffers created with `CL_MEM_USE_HOST_PTR` need to provide an appropriately aligned host memory pointer that is aligned to the data types used to access these buffers in a kernel(s).
As well, the user is responsible to ensure that data passed into and out of OpenCL images are properly aligned to the granularity of the data representing a single pixel (e.g.
`image_num_channels` * `sizeof`(`image_channel_data_type`)) except for `CL_RGB` and `CL_RGBx` images where the data must be aligned to the granularity of a single channel in a pixel (i.e.
`sizeof`(`image_channel_data_type`)).
This implies that OpenCL images created with `CL_MEM_USE_HOST_PTR` must align correctly.
The image alignment value can be queried using the `CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT` query.
In addition, source pointers for <<clEnqueueWriteBuffer.adoc#, `clEnqueueWriteBuffer`>>, <<clEnqueueWriteImage.adoc#, `clEnqueueWriteImage`>> and other operations that copy to the OpenCL runtime, as well as destination pointers for <<clEnqueueReadBuffer.adoc#, `clEnqueueReadBuffer`>>, <<clEnqueueReadImage.adoc#, `clEnqueueReadImage`>> and other operations that copy from the OpenCL runtime must follow the same alignment rules.

OpenCL makes no requirement about the alignment of OpenCL application defined data types outside of buffers and images, except that the underlying vector primitives (e.g.
`__cl_float4`) where defined shall be directly accessible as such using appropriate named fields in the `cl_type` union.
Nevertheless, it is recommended that the `cl_platform.h` header should attempt to naturally align OpenCL defined application data types (e.g.
`cl_float4`) according to their type.


:spec-name: CLan
:spec-page: 6

include::_footer.adoc[]
