include::_header.adoc[]


[[get_local_size]]
= get_local_size

Returns the number of local work-items in the specified dimension.

[source,c]
----
size_t get_local_size(uint dimindx)
----


[[description]]
== Description

Returns the number of local work-items specified in dimension identified by `dimindx`.
This value is at most the value given by the `local_work_size` argument to <<clEnqueueNDRangeKernel.adoc#, `clEnqueueNDRangeKernel`>> if `local_work_size` is not NULL; otherwise the OpenCL implementation chooses an appropriate `local_work_size` value which is returned by this function.
If the kernel is executed with a nonuniform work-group size (i.e.
the `global_work_size` values specified to <<clEnqueueNDRangeKernel.adoc#, `clEnqueueNDRangeKernel`>> are not evenly divisable by the `local_work_size` values for each dimension), calls to this built-in from some work-groups may return different values than calls to this built-in from other work-groups.

Valid values of `dimindx` are 0 to <<get_work_dim.adoc#, `get_work_dim`>>() - 1.
For other values of `dimindx`, `get_local_size`() returns 1.


:spec-name: CLan
:spec-page: 69


[[seealso]]
== Also see

<<workItemFunctions.adoc#, Work-Item Functions>>, <<clEnqueueNDRangeKernel.adoc#, `clEnqueueNDRangeKernel`>>

include::_footer.adoc[]
