include::_header.adoc[]


[[__global]]
= __global

Address space qualifier.

----
__global
global
----


[[description]]
== Description

The `__global` or `global` address space name is used to refer to memory objects (buffer or image objects) allocated from the global memory pool.

A buffer memory object can be declared as a pointer to a scalar, vector or user-defined struct.
This allows the kernel to read and/or write any location in the buffer.

The actual size of the array memory object is determined when the memory object is allocated via appropriate API calls in the host code.

As image objects are always allocated from the global address space, the `__global` or `global` qualifier should not be specified for image types.
The elements of an image object cannot be directly accessed.
Built-in functions to read from and write to an image object are provided.

Variables defined at program scope and static variables inside a function can also be declared in the `global` address space.
They can be defined with any valid OpenCL C data type except for those in table 6.3.
In particular, such program scope variables may be of any user-defined type, or a pointer to a user-defined type.
In the presence of shared virtual memory, these pointers or pointer members should work as expected as long as they are shared virtual memory pointers and the referenced storage has been mapped appropriately.
These variables in the `global` address space have the same lifetime as the program, and their values persist between calls to any of the kernels in the program.
These variables are not shared across devices.
They have distinct storage.

Program scope and static variables in the `global` address space may be initialized, but only with constant expressions.

The `const` qualifier can also be used with the `__global` qualifier to specify a read-only buffer memory object.


[[notes]]
== Notes

include::addressSpaceQualifiersInc.adoc[]


[[example1]]
== Examples

include::qualifierExampleInc.adoc[]

----
global float4  *color;      // An array of float4 elements
typedef struct {
      float a[3];
      int   b[2];
} foo_t;
global foo_t   *my_info;    // An array of foo_t elements.
----

----
global int foo;         // OK.
int foo;                // OK. Declared in the global address space
global uchar buf[512];  // OK.
global int baz = 12;    // OK. Initialization is allowed
static global int bat;  // OK. Internal linkage

global uchar bigbuf[CL_DEVICE_MAX_GLOBAL_VARIABLE_SIZE]; // OK.

static int foo;         // OK. Declared in the global address space
static global int foo;  // OK.

int *foo;               // OK. foo is allocated in global address space.
                        // pointer to foo in generic address space

void func(...)
{
   int *foo;            // OK. foo is allocated in private address space.
                        // foo points to a location in generic address space.
   ...
}

global int * global ptr;          // OK.
int * global ptr;                 // OK.
constant int *global ptr=&baz;    // error since baz is in global address
                                  // space.
global int * constant ptr = &baz; // OK

// Pointers work. Also, initialization to a constant known at
// program load time
global int *global baz_ptr = &baz;

global image2d_t im;       // Error. Invalid type for program scope
                           // variables

global event_t ev;   // Error. Invalid type for program scope variables

global int *bad_ptr; // Error. No implicit address space
----


:spec-name: CLan
:spec-page: 34


[[seealso]]
== Also see

<<local.adoc#, `__local`>>, <<constant.adoc#, `__constant`>>, <<private.adoc#, `__private`>>, <<qualifiers.adoc#, `qualifiers`>>

include::_footer.adoc[]
