include::_header.adoc[]


[[ldexp]]
= ldexp

Multiply `x` by 2 to the power `k`.

[source,c]
----
float n ldexp(float n x,
              int n k)

float n ldexp(float n x,
              int k)

float ldexp(float x,
            int k)

double n ldexp(double n x,
               int n k)

double n ldexp(double n x,
               int k)

double ldexp(double x,
             int n)

half n ldexp(half n x,
             int n k)

half n ldexp(half n x,
             int k)

half ldexp(half x,
           int k)
----


[[description]]
== Description

Multiply `x` by 2 to the power `k`.


[[notes]]
== Notes

The vector versions of the math functions operate component-wise.
The description is per-component.

The built-in math functions are not affected by the prevailing rounding mode in the calling environment, and always return the same value as they would if called with the round to nearest even rounding mode.

The built-in math functions take scalar or vector arguments.
The generic type name `gentype` is used to indicate that the function can take `float`, `float2`, `float3`, `float4`, `float8`, or `float16` as the type for the arguments.
For any specific use of these function, the actual type has to be the same for all arguments and the return type.

If extended with <<cl_khr_fp16.adoc#, `cl_khr_fp16`>>, generic type name `gentype` may indicate `half` and `half{2|3|4|8|16}` as arguments and return values.


:spec-name: CLan
:spec-page: 72


[[seealso]]
== Also see

<<mathFunctions.adoc#, Math Functions>>

include::_footer.adoc[]
