include::_header.adoc[]


[[read_image2d]]
= read_imagef (1D)

Do an element lookup in the 1D image object, returning floating-point values.

[source,c]
----
float4 read_imagef(read_only image1d_t image,
                   sampler_t sampler,
                   int coord)

float4 read_imagef(read_only image1d_t image,
                   sampler_t sampler,
                   float coord)

float4 read_imagef(read_only image1d_array_t image,
                   sampler_t sampler,
                   float2 coord)

float4 read_imagef(image1d_t image,
                   sampler_t sampler,
                   float coord,
                   float lod)

float4 read_imagef(image1d_t image,
                   sampler_t sampler,
                   float coord,
                   float gradient_x,
                   float gradient_y)

float4 read_imagef(image1d_array_t image,
                   sampler_t sampler,
                   float2 coord,
                   float lod)

float4 read_imagef(image1d_array_t image,
                   sampler_t sampler,
                   float2 coord,
                   float gradient_x,
                   float gradient_y)
----


[[description]]
== Functions to read 1D images and image arrays

For forms that take `image1d_t`, use _coord_ to do an element lookup in the 1D image object specified by `image`.

For forms that take `image1d_array_t`, use _coord.x_ to do an element lookup in the 1D image identified by _coord.y_ in the 1D image array specified by `image`.

The samplerless read image functions behave exactly as the corresponding read image functions that take integer coordinates and a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode to `CLK_ADDRESS_NONE`.

`read_imagef` returns floating-point values in the range [0.0... 1.0] for image objects created with `image_channel_data_type` set to one of the predefined packed formats or `CL_UNORM_INT8` or `CL_UNORM_INT16`.

`read_imagef` returns floating-point values in the range [-1.0... 1.0] for image objects created with `image_channel_data_type` set to `CL_SNORM_INT8`, or `CL_SNORM_INT16`.

`read_imagef` returns floating-point values for image objects created with `image_channel_data_type` set to `CL_HALF_FLOAT` or `CL_FLOAT`.

The `read_imagef` calls that take integer coordinates must use a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.

If the <<cl_khr_mipmap_image.adoc#, `cl_khr_mipmap_image`>> extension is supported, The image read and write functions (see sections 6.13.14.2, 6.13.14.3 and 6.13.14.4) read from and write to mip-level 0 if the image argument is a mip-mapped image.

include::imageMipmapFunctions1DInc.adoc[]


[[notes]]
== Notes

General information about the `read_image`* functions follows.

include::imageFunctionsInc.adoc[]

include::imageMappingInc.adoc[]


:spec-name: CLan
:spec-page: 127


[[seealso]]
== Also see

<<imageFunctions.adoc#, Image Functions>>, <<cl_khr_mipmap_image.adoc#, `cl_khr_mipmap_image`>>, <<sampler_t.adoc#, `sampler_t`>>

include::_footer.adoc[]
