include::_header.adoc[]


[[read_image2d]]
= read_imagef (2D)

Do an element lookup in the 2D image object, returning floating-point values.

[source,c]
----
float4 read_imagef(read_only image2d_t image,
                   sampler_t sampler,
                   int2 coord)

float4 read_imagef(read_only image2d_t image,
                   sampler_t sampler,
                   float2 coord)

float4 read_imagef(aQual image2d_t image,
                   int2 coord)

float4 read_imagef(aQual image2d_array_t image,
                   int4 coord)

float4 read_imagef(aQual image2d_depth_t image,
                   int2 coord)

float4 read_imagef(aQual image2d_array_depth_t image,
                   int4 coord)

float4 read_imagef(read_only image2d_array_t image,
                   sampler_t sampler,
                   int4 coord)

float4 read_imagef(read_only image2d_array_t image,
                   sampler_t sampler,
                   float4 coord)

float read_imagef(read_only image2d_depth_t image,
                  sampler_t sampler,
                  int2 coord)

float read_imagef(read_only image2d_depth_t image,
                  sampler_t sampler,
                  float2 coord)

float read_imagef(read_only image2d_array_depth_t image,
                  sampler_t sampler,
                  int4 coord)

float read_imagef(read_only image2d_array_depth_t image,
                  sampler_t sampler,
                  float4 coord)

float4 read_imagef(image2d_t image,
                   sampler_t sampler,
                   float2 coord,
                   float lod)

float read_imagef(image2d_depth_t image,
                  sampler_t sampler,
                  float2 coord,
                  float lod)

float4 read_imagef(image2d_t image,
                   sampler_t sampler,
                   float2 coord,
                   float2 gradient_x,
                   float2 gradient_y)

float read_imagef(image2d_depth_t image,
                  sampler_t sampler,
                  float2 coord,
                  float2 gradient_x,
                  float2 gradient_y)

float4 read_imagef(image2d_array_t image,
                   sampler_t sampler,
                   float4 coord,
                   float lod)

float read_imagef(image2d_array_depth_t image,
                  sampler_t sampler,
                  float4 coord,
                  float lod)

float4 read_imagef(image2d_array_t image,
                   sampler_t sampler,
                   float4 coord,
                   float2 gradient_x,
                   float2 gradient_y)

float read_imagef(image2d_array_depth_t image,
                  sampler_t sampler,
                  float4 coord,
                  float2 gradient_x,
                  float2 gradient_y)

float4 read_imagef(image2d_msaa_t image,
                   int2 coord,
                   int sample)

float4 read_imagef(image2d_array_msaa_t image,
                   int4 coord,
                   int sample)

float read_imagef(image2d_msaa_depth_t image,
                  int2 coord,
                  int sample)

float read_imagef(image2d_array_msaa_depth_t image,
                  int4 coord,
                  int sample)
----


[[description]]
== Description

`aQual` refers to one of the access qualifiers `read_only`, `write_only`, or `read_write`.
For samplerless read functions this may be `read_only` or `read_write`.

.Non-mipmap forms that take `image2d_t` and return `float4:`

Use (`coord.x`, `coord.y`) to do an element lookup in the 2D image object specified by `image`.

`read_imagef` returns floating-point values in the range [0.0... 1.0] for image objects created with `image_channel_data_type` set to one of the predefined packed formats or `CL_UNORM_INT8` or `CL_UNORM_INT16`.

`read_imagef` returns floating-point values in the range [-1.0... 1.0] for image objects created with `image_channel_data_type` set to `CL_SNORM_INT8`, or `CL_SNORM_INT16`.

`read_imagef` returns floating-point values for image objects created with `image_channel_data_type` set to `CL_HALF_FLOAT` or `CL_FLOAT`.

The `read_imagef` calls that take integer coordinates must use a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.

.Non-mipmap forms that take `image2d_array_t` and return `float4:`

Use _coord.xy_ to do an element lookup in the 2D image identified by _coord.z_ in the 2D image array specified by `image`.

`read_imagef` returns floating-point values in the range [0.0... 1.0] for image objects created with `image_channel_data_type` set to one of the predefined packed formats or `CL_UNORM_INT8` or `CL_UNORM_INT16`.

`read_imagef` returns floating-point values in the range [-1.0... 1.0] for image objects created with `image_channel_data_type` set to `CL_SNORM_INT8`, or `CL_SNORM_INT16`.

`read_imagef` returns floating-point values for image objects created with `image_channel_data_type` set to `CL_HALF_FLOAT` or `CL_FLOAT`.

The `read_imagef` calls that take integer coordinates must use a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.

.Non-mipmap forms that take `image2d_depth_t` and return `float:`

Use (`coord.x`, `coord.y`) to do an element lookup in the 2D depth image object specified by `image`.

`read_imagef` returns a floating-point value in the range [0.0... 1.0] for depth image objects created with `image_channel_data_type` set to `CL_UNORM_INT16` or `CL_UNORM_INT24`.

`read_imagef` returns a floating-point value for depth image objects created with `image_channel_data_type` set to `CL_FLOAT`.

The `read_imagef` calls that take integer coordinates must use a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

Values returned by `read_imagef` for depth image objects with `image_channel_data_type` values not specified in the description above are undefined.

.Non-mipmap forms that take `image2d_array_depth_t` and return `float:`

Use _coord.xy_ to do an element lookup in the 2D image identified by _coord.z_ in the 2D depth image array specified by `image`.

`read_imagef` returns a floating-point value in the range [0.0... 1.0] for depth image objects created with `image_channel_data_type` set to `CL_UNORM_INT16` or `CL_UNORM_INT24`.

`read_imagef` returns a floating-point value for depth image objects created with `image_channel_data_type` set to `CL_FLOAT`.

The `read_imagef` calls that take integer coordinates must use a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

Values returned by `read_imagef` for depth image objects with `image_channel_data_type` values not specified in the description above are undefined.

include::imageMipmapFunctions2DInc.adoc[]

.For forms that take image2d_msaa_t and return float4:

Use the coordinate (`coord.x, coord.y`) and `sample` to do an element lookup in the 2D image object specified by `image`.

`read_imagef` returns floating-point values in the range [0.0 … 1.0] for image objects created with `image_channel_data_type` set to one of the predefined packed formats or `CL_UNORM_INT8`, or `CL_UNORM_INT16`.

`read_imagef` returns floating-point values in the range [-1.0 … 1.0] for image objects created with `image_channel_data_type` set to `CL_SNORM_INT8`, or `CL_SNORM_INT16`.

`read_imagef` returns floating-point values for image objects created with `image_channel_data_type` set to `CL_HALF_FLOAT` or `CL_FLOAT`.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.

.For forms that take image2d_array_msaa_t and return float4:

Use `coord.xy` and `sample` to do an element lookup in the 2D image identified by `coord.z` in the 2D image array specified by `image`.

`read_imagef` returns floating-point values in the range [0.0 … 1.0] for image objects created with `image_channel_data_type` set to one of the predefined packed formats or `CL_UNORM_INT8`, or `CL_UNORM_INT16`.

`read_imagef` returns floating-point values in the range [-1.0 … 1.0] for image objects created with `image_channel_data_type` set to `CL_SNORM_INT8`, or `CL_SNORM_INT16`.

`read_imagef` returns floating-point values for image objects created with `image_channel_data_type` set to `CL_HALF_FLOAT` or `CL_FLOAT`.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.

.For forms that take image2d_msaa_depth_t and return float:

Use the coordinate (`coord.x, coord.y`) and `sample` to do an element lookup in the 2D depth image object specified by `image`.

`read_imagef` returns a floating-point value in the range [0.0 … 1.0] for depth image objects created with `image_channel_data_type` set to `CL_UNORM_INT16` or `CL_UNORM_INT24`.

`read_imagef` returns a floating-point value for depth image objects created with `image_channel_data_type` set to `CL_FLOAT`.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.

.For forms that take image2d_array_msaa_depth_t and return float:

Use `coord.xy` and `sample` to do an element lookup in the 2D image identified by `coord.z` in the 2D depth image array specified by `image`.

`read_imagef` returns a floating-point value in the range [0.0 … 1.0] for depth image objects created with `image_channel_data_type` set to `CL_UNORM_INT16` or `CL_UNORM_INT24`.

`read_imagef` returns a floating-point value for depth image objects created with `image_channel_data_type` set to `CL_FLOAT`.

Values returned by `read_imagef` for image objects with `image_channel_data_type` values not specified in the description above are undefined.


[[notes]]
== Notes

General information about the `read_image`* functions follows.

include::imageFunctionsInc.adoc[]

include::imageMappingInc.adoc[]


:spec-name: CLan
:spec-page: 127


[[seealso]]
== Also see

<<imageFunctions.adoc#, Image Functions>>, <<cl_khr_mipmap_image.adoc#, `cl_khr_mipmap_image`>>, <<sampler_t.adoc#, `sampler_t`>>, <<cl_khr_gl_msaa_sharing.adoc#, `cl_khr_gl_msaa_sharing`>>

include::_footer.adoc[]
