include::_header.adoc[]


[[read_image1d]]
= read_image{i|ui} (1D)

Do an element lookup in the 1D image object, returning unnormalized signed integer and unsigned integer values.

[source,c]
----
int4 read_imagei(read_only image1d_t image,
                 sampler_t sampler,
                 int coord)

int4 read_imagei(read_only image1d_t image,
                 sampler_t sampler,
                 float coord)

uint4 read_imageui(read_only image1d_t image,
                   sampler_t sampler,
                   int coord)

uint4 read_imageui(read_only image1d_t image,
                   sampler_t sampler,
                   float coord)

int4 read_imagei(read_only image1d_array_t image,
                 sampler_t sampler,
                 int2 coord)

int4 read_imagei(read_only image1d_array_t image,
                 sampler_t sampler,
                 float2 coord)

uint4 read_imageui(read_only image1d_array_t image,
                   sampler_t sampler,
                   int2 coord)

uint4 read_imageui(read_only image1d_array_t image,
                   sampler_t sampler,
                   float2 coord)

int4 read_imagei(aQual image1d_t image,
                 int coord)

uint4 read_imageui(aQual image1d_t image,
                   int coord)

int4 read_imagei(aQual image1d_buffer_t image,
                 int coord)

uint4 read_imageui(aQual image1d_buffer_t image,
                   int coord)

int4 read_imagei(aQual image1d_array_t image,
                 int2 coord)

uint4 read_imageui(aQual image1d_array_t image,
                   int2 coord)

int4 read_imagei(image1d_t image,
                 sampler_t sampler,
                 float coord,
                 float lod)

uint4 read_imageui(image1d_t image,
                   sampler_t sampler,
                   float coord,
                   float lod)

int4 read_imagei(image1d_t image,
                 sampler_t sampler,
                 float coord,
                 float gradient_x,
                 float gradient_y)

uint4 read_imageui(image1d_t image,
                   sampler_t sampler,
                   float coord,
                   float gradient_x,
                   float gradient_y)

int4 read_imagei(image1d_array_t image,
                 sampler_t sampler,
                 float2 coord,
                 float lod)

uint4 read_imageui(image1d_array_t image,
                   sampler_t sampler,
                   float2 coord,
                   float lod)

int4 read_imagei(image1d_array_t image,
                 sampler_t sampler,
                 float2 coord,
                 float gradient_x,
                 float gradient_y)

uint4 read_imageui(image1d_array_t image,
                   sampler_t sampler,
                   float2 coord,
                   float gradient_x,
                   float gradient_y)
----


[[description]]
== Description

`aQual` refers to one of the access qualifiers `read_only`, `write_only`, or `read_write`.
For samplerless read functions this may be `read_only` or `read_write`.

For the forms that take an `image1d_t`, use `coord` to do an element lookup in the 1D image object specified by `image`.

For the forms that take an `image1d_array_t`, use _coord.x_ to do an element lookup in the 1D image identified by _coord.y_ in the 1D image array specified by `image`.

`read_imagei` and `read_imageui` return unnormalized signed integer and unsigned integer values respectively.
Each channel will be stored in a 32-bit integer.

`read_imagei` can only be used with image objects created with `image_channel_data_type` set to one of the following values: `CL_SIGNED_INT8`, `CL_SIGNED_INT16`, or `CL_SIGNED_INT32`.
If the `image_channel_data_type` is not one of the above values, the values returned by `read_imagei` are undefined.

`read_imageui` can only be used with image objects created with `image_channel_data_type` set to one of the following values: `CL_UNSIGNED_INT8`, `CL_UNSIGNED_INT16`, and `CL_UNSIGNED_INT32`.
If the `image_channel_data_type` is not one of the above values, the values returned by `read_imageui` are undefined.

The `read_imagei` and `read_imageui` calls support a nearest filter only.
The `filter_mode` specified in `sampler` must be set to `CLK_FILTER_NEAREST`; otherwise the values returned are undefined.

Furthermore, the `read_imagei` returned are undefined.
and `read_imageui` calls that take integer coordinates must use a returned are undefined.
sampler with normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

include::imageMipmapFunctions1DInc.adoc[]


[[notes]]
== Notes

include::imageFunctionsInc.adoc[]

include::imageMappingInc.adoc[]


:spec-name: CLan
:spec-page: 127


[[seealso]]
== Also see

<<imageFunctions.adoc#, Image Functions>>, <<cl_khr_mipmap_image.adoc#, `cl_khr_mipmap_image`>>, <<sampler_t.adoc#, `sampler_t`>>

include::_footer.adoc[]
