include::_header.adoc[]


[[read_image2d]]
= read_image{i|ui} (2D)

Do an element lookup in the 2D image object, returning unnormalized signed integer and unsigned integer values.

[source,c]
----
int4 read_imagei(read_only image2d_t image,
                 sampler_t sampler,
                 int2 coord)

int4 read_imagei(read_only image2d_t image,
                 sampler_t sampler,
                 float2 coord)

uint4 read_imageui(read_only image2d_t image,
                   sampler_t sampler,
                   int2 coord)

uint4 read_imageui(read_only image2d_t image,
                   sampler_t sampler,
                   float2 coord)

int4 read_imagei(read_only image2d_array_t image,
                 sampler_t sampler,
                 int4 coord)

int4 read_imagei(read_only image2d_array_t image,
                 sampler_t sampler,
                 float4 coord)

uint4 read_imageui(read_only image2d_array_t image,
                   sampler_t sampler,
                   int4 coord)

uint4 read_imageui(read_only image2d_array_t image,
                   sampler_t sampler,
                   float4 coord)

int4 read_imagei(aQual image2d_t image,
                 int2 coord)

uint4 read_imageui(aQual image2d_t image,
                   int2 coord)

int4 read_imagei(aQual image2d_array_t image,
                 int4 coord)

uint4 read_imageui(aQual image2d_array_t image,
                   int4 coord)

int4 read_imagei(image2d_t image,
                 sampler_t sampler,
                 float2 coord,
                 float lod)

uint4 read_imageui(image2d_t image,
                   sampler_t sampler,
                   float2 coord,
                   float lod)

int4 read_imagei(image2d_t image,
                 sampler_t sampler,
                 float2 coord,
                 float2 gradient_x,
                 float2 gradient_y)

uint4 read_imageui(image2d_t image,
                   sampler_t sampler,
                   float2 coord,
                   float2 gradient_x,
                   float2 gradient_y)

int4 read_imagei(image2d_array_t image,
                 sampler_t sampler,
                 float4 coord,
                 float lod)

uint4 read_imageui(image2d_array_t image,
                   sampler_t sampler,
                   float4 coord,
                   float lod)

int4 read_imagei(image2d_array_t image,
                 sampler_t sampler,
                 float4 coord,
                 float2 gradient_x,
                 float2 gradient_y)

uint4 read_imageui(image2d_array_t image,
                   sampler_t sampler,
                   float4 coord,
                   float2 gradient_x,
                   float2 gradient_y)

int4 read_imagei(image2d_msaa_t image,
                 int2 coord,
                 int sample)

uint4 read_imageui(image2d_msaa_t image,
                   int2 coord,
                   int sample)

int4 read_imagei(image2d_array_msaa_t image,
                 int4 coord,
                 int sample)

uint4 read_imageui(image2d_array_msaa_t image,
                   int4 coord,
                   int sample)
----


[[description]]
== Description

`aQual` refers to one of the access qualifiers `read_only`, `write_only`, or `read_write`.
For samplerless read functions this may be `read_only` or `read_write`.

For the forms that take an `image2d_t` object, use the coordinate _(coord.x, coord.y)_ to do an element lookup in the 2D image object specified by `image`.

For the forms that take an `image2d_array_t` object, use the gradients to compute the lod and coordinate _coord.xy_ to do an element lookup in the mip-level specified by the computed lod in the 2D image object specified by `image`.

For the forms that take an `image2d_t` object and gradients, use _coord.xy_ to do an element lookup in the 2D image identified by _coord.z_ in the 2D image array specified by `image`.

For forms that take `image2d_msaa_t`, use the coordinate (`coord.x, coord.y`) and `sample` to do an element lookup in the 2D image object specified by `image`.

For forms that take `image2d_array_msaa_t`, use `coord.xy` and `sample` to do an element lookup in the 2D image identified by `coord.z` in the 2D image array specified by `image`.

The samplerless read image functions behave exactly as the corresponding read image functions that take integer coordinates and a sampler with filter mode set to `CLK_FILTER_NEAREST`, normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode to `CLK_ADDRESS_NONE`.

`read_imagei` and `read_imageui` return unnormalized signed integer and unsigned integer values respectively.
Each channel will be stored in a 32-bit integer.

`read_imagei` can only be used with image objects created with `image_channel_data_type` set to one of the following values: `CL_SIGNED_INT8`, `CL_SIGNED_INT16`, or `CL_SIGNED_INT32`.
If the `image_channel_data_type` is not one of the above values, the values returned by `read_imagei` are undefined.

`read_imageui` can only be used with image objects created with `image_channel_data_type` set to one of the following values: `CL_UNSIGNED_INT8`, `CL_UNSIGNED_INT16`, and `CL_UNSIGNED_INT32`.
If the `image_channel_data_type` is not one of the above values, the values returned by `read_imageui` are undefined.

For the forms that take a sampler, the `read_imagei` and `read_imageui` calls support a nearest filter only.
The `filter_mode` specified in `sampler` must be set to `CLK_FILTER_NEAREST`; otherwise the values returned are undefined.

Furthermore, for the forms that take a sampler, the `read_imagei` and `read_imageui` calls that take integer coordinates must use a sampler with normalized coordinates set to `CLK_NORMALIZED_COORDS_FALSE` and addressing mode set to `CLK_ADDRESS_CLAMP_TO_EDGE`, `CLK_ADDRESS_CLAMP` or `CLK_ADDRESS_NONE`; otherwise the values returned are undefined.

include::imageMipmapFunctions2DInc.adoc[]


[[notes]]
== Notes

include::imageFunctionsInc.adoc[]

include::imageMappingInc.adoc[]


:spec-name: CLan
:spec-page: 127


[[seealso]]
== Also see

<<imageFunctions.adoc#, Image Functions>>, <<cl_khr_mipmap_image.adoc#, `cl_khr_mipmap_image`>>, <<sampler_t.adoc#, `sampler_t`>>, <<cl_khr_gl_msaa_sharing.adoc#, `cl_khr_gl_msaa_sharing`>>

include::_footer.adoc[]
