include::_header.adoc[]


[[restrictionsref]]
= Restrictions

* {blank}
+
--

The use of pointers is somewhat restricted.
The following rules apply:

* Arguments to kernel functions declared in a program that are pointers must be declared with the <<global.adoc#, `__global`>>, <<constant.adoc#, `__constant`>>, or <<local.adoc#, `__local`>> qualifier.

* A pointer declared with the <<constant.adoc#, `__constant`>> qualifier can only be assigned to a pointer declared with the __constant qualifier.

* Pointers to functions are not allowed.

--

* {blank}
+
--

An image type ( <<otherDataTypes.adoc#, `image2d_t`>>, <<otherDataTypes.adoc#, `image3d_t`>>, <<otherDataTypes.adoc#, `image2d_array_t`>>, <<otherDataTypes.adoc#, `image1d_t`>>, <<otherDataTypes.adoc#, `image1d_buffer_t`>>, or <<otherDataTypes.adoc#, `image1d_array_t`>>) can only be used as the type of a function argument.
An image function argument cannot be modified.
Elements of an image can only be accessed using the <<imageFunctions.adoc#, Built-in Image Functions>>.

An image type cannot be used to declare a variable, a structure or union field, an array of images, a pointer to an image, or the return type of a function.
An image type cannot be used with the <<global.adoc#, `__global`>>, <<private.adoc#, `__private`>>, <<local.adoc#, `__local`>> and <<constant.adoc#, `__constant`>> address space qualifiers.

The sampler type (<<sampler_t.adoc#, `sampler_t`>>) can only be used as the type of a function argument or a variable declared in the program scope or the outermost scope of a kernel function.
The behavior of a sampler variable declared in a non-outermost scope of a kernel function is implementation-defined.
A sampler argument or variable cannot be modified.

The sampler type cannot be used to declare a structure or union field, an array of samplers, a pointer to a sampler, or the return type of a function.
The sampler type cannot be used with the <<local.adoc#, `__local`>> and <<global.adoc#, `__global`>> address space qualifiers.

--

* Bit-fields struct members are currently not supported.

* Variable length arrays and structures with flexible (or unsized) arrays are not supported.

* Variadic macros and functions with the exception of <<printfFunction.adoc#, `printf`>> and <<enqueue_kernel.adoc#, `enqueue_kernel`>> are not supported.

* The library functions defined in the C99 standard headers `assert.h`, `ctype.h`, `complex.h`, `errno.h`, `fenv.h`, `float.h`, `inttypes.h`, `limits.h`, `locale.h`, `setjmp.h`, `signal.h`, `stdarg.h`, `stdio.h`, `stdlib.h`, `string.h`, `tgmath.h`, `time.h`, `wchar.h`, and `wctype.h` are not available and cannot be included by a program.

* The `auto` and `register` storage-class specifiers are not supported.

* Recursion is not supported.

* The return type of a kernel function must be `void`.

* Arguments to kernel functions in a program cannot be declared with the built-in scalar types `bool`, `half`, `size_t`, `ptrdiff_t`, `intptr_t`, and `uintptr_t`, or a struct and/or union that contain fields declared to be one of these built-in scalar types.
The size in bytes of these types except `half` are implementation-defined and in addition can also be different for the OpenCL device and the host processor making it difficult to allocate buffer objects to be passed as arguments to a kernel declared as pointer to these types.
`half` is not supported as `half` can be used as a storage format only (unless the <<cl_khr_fp16.adoc#, `cl_khr_fp16`>> extension is supported) and is not a data type on which floating-point arithmetic can be performed.

* Whether or not irreducible control flow is illegal is implementation defined.

* The type qualifiers `const`, `restrict` and `volatile` as defined by the C99 specification are supported.
These qualifiers cannot be used with <<otherDataTypes.adoc#, `image2d_t`>>, <<otherDataTypes.adoc#, `image3d_t`>>, <<otherDataTypes.adoc#, `image2d_array_t`>>, <<otherDataTypes.adoc#, `image2d_depth_t`>>, <<otherDataTypes.adoc#, `image2d_array_depth_t`>>, <<otherDataTypes.adoc#, `image1d_t`>>, <<otherDataTypes.adoc#, `image1d_buffer_t`>> and <<otherDataTypes.adoc#, `image1d_array_t`>> types.
Types other than pointer types shall not use the `restrict` qualifier.

* The event type (<<otherDataTypes.adoc#, `event_t`>>) cannot be used as the type of a kernel function argument.
The event type cannot be used to declare a program scope variable.
The event type cannot be used to declare a structure or union field.
The event type cannot be used with the <<local.adoc#, `__local`>>, <<constant.adoc#, `__constant`>> and <<global.adoc#, `__global`>> address space qualifiers.

* The `clk_event_t`, `ndrange_t` and `reserve_id_t` types cannot be used as arguments to kernel functions that get enqueued from the host.
The `clk_event_t` and `reserve_id_t` types cannot be declared in program scope.

* The behavior of applying the `sizeof` operator to the `queue_t`, `clk_event_t`, `ndrange_t` and `reserve_id_t` types is implementation-defined.

* Kernels enqueued by the host must continue to have their arguments that are a pointer to a type declared to point to a named address space.

* A function in an OpenCL program cannot be called `main`.


:spec-name: CLan
:spec-page: 51


[[seealso]]
== Also see

<<imageFunctions.adoc#, Image Functions>>, <<functionQualifiers.adoc#, Function Qualifiers>>, <<qualifiers.adoc#, Qualifiers>>

include::_footer.adoc[]
