include::_header.adoc[]


[[vstorea_halfn]]
= vstorea_half`n`

Convert float vector to half vector and write to a pointer to memory.

[source,c]
----
void vstorea_half n(float n data,
                    size_t offset,
                    half *p)

void vstorea_half n _rte(float n data,
                         size_t offset,
                         half *p)

void vstorea_half n _rtz(float n data,
                         size_t offset,
                         half *p)

void vstorea_half n _rtp(float n data,
                         size_t offset,
                         half *p)

void vstorea_half n _rtn(float n data,
                         size_t offset,
                         half *p)
----

[source,c]
----
void vstorea_half n(double n data,
                    size_t offset,
                    half *p)

void vstorea_half n _rte(double n data,
                         size_t offset,
                         half *p)

void vstorea_half n _rtz(double n data,
                         size_t offset,
                         half *p)

void vstorea_half n _rtp(double n data,
                         size_t offset,
                         half *p)

void vstorea_half n _rtn(double n data,
                         size_t offset,
                         half *p)
----


[[description]]
== Description

The `floatn` (or `doublen`) value given by `data` is converted to a `halfn` value using the appropriate rounding mode.

For n = 2, 4, 8 and 16, the `halfn` value is written to the address computed as (`p` + (`offset` * `n`)).
The address computed as (`p` + (`offset` * `n`)) must be aligned to sizeof (halfn) bytes.

For n = 3, the `half3` value is written to the address computed as (`p` + (`offset` * 4)).
The address computed as (`p` + (`offset` * 4)) must be aligned to sizeof (half) * 4 bytes.

`vstorea_halfn` uses the default rounding mode.
The default rounding mode is round to the nearest even.

An application that wants to use `half` and `halfn` types will need to include the `#pragma OPENCL EXTENSION cl_khr_fp16 : enable` directive.


[[notes]]
== Notes

include::vectorFunctionsInc.adoc[]

`vstorea_half3` writes `x`, `y`, `z` components from a 3-component vector to address (`p` + (`offset` * 4)).


:spec-name: CLan
:spec-page: 93


[[seealso]]
== Also see

<<vectorDataLoadandStoreFunctions.adoc#, Vector Data Load and Store Functions>>

include::_footer.adoc[]
